services:
  marvel_characters:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ENV=local
    env_file:
      - .env.local
    volumes:
      - data:/app/data/

volumes:
  data:
